apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/cb-kubecd/my-cool-app-jr4:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/cb-kubecd/my-cool-app-jr4:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: my-cool-app-jr4
        chartPath: charts/my-cool-app-jr4
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/cb-kubecd/my-cool-app-jr4'
          image.tag: '{{.DIGEST_HEX}}'
